### ISSUE TITLE
Passenger official support for newer nginx packages on EL8 distros after CentOS 8 EOL?

### ISSUE THREAD

**Issue by pgill98** [phusion/passenger_rpm_automation#18]
Hi @CamJN and the rest of the Passenger team,

First off, thanks for all the work that the team has been putting for maintaining Passenger, we appreciate it :). 

As you all may have heard CentOS 7 and CentOS 8 are being put on EOL by 2024 and Dec. 2021 respectively and because of that a lot of users are forced to upgrade from CentOS 8 to another EL8 based distro (AlmaLinux 8, Rocky Linux 8, Oracle EL 8) which are all 1:1 binary compatible with RHEL 8 based distros. 

My team and I are one of the people being forced to switch distros, specifically to AlmaLinux 8, as it is 1:1 binary compatible production-grade replacement after CentOS is discontinued (https://thehackernews.com/2021/09/moving-forward-after-centos-8-eol.html). It would be great and helpful to us and I am sure many others if you guys are able to add Passenger official support for a "packaged nginx dynamic module" that is compatible with nginx 1.20.x before the CentOS 8 EOL date (12/31/2021) that way everyone upgrading from CentOS 7/8 to AlmaLinux 8 / EL8 distros can installed a "packaged" Passenger dynamic module compatible with nginx 1.20.x without any issues.

Everyone is forced to upgrade from CentOS 8 ASAP To AlmaLinux 8 or RockyLinux 8 which are both compatible with RHEL 8 and I am sure this would make everyone's lives easier. Also, when will this page (https://www.phusionpassenger.com/library/install/nginx/install/oss/) include official instructions from Phusion Passenger? (Right now, it only contains RHEL/CentOS 6 and RHEL/CentOS 7) and the other developers and me are concerned about the fact that compiling from the source will make everything harder as it already is considering everyone is migrating from a different OS right now.

Also, your build bot doesn't work with the official Nginx repositories. It has some issue with nginx official source repositories and requires manual work, however, you guys might want to consider using the EPEL repos as you all have experience with it and EPEL has source rpm files available for nginx 1.20.x
1. AlmaLinux source rpm link: "https://repo.almalinux.org/almalinux/8.5/AppStream/Source/Packages/"
2. EPEL 8 source rpm link: "https://dl.fedoraproject.org/pub/epel/8/Modular/source/tree/Packages/n/"
I hope this makes it easier to automate this and help all the other nginx+passenger users.

Thanks for all the hard work!

**Comment by CamJN** [comment]
Those docs are old and kept for legacy purposes, the new docs are here: https://www.phusionpassenger.com/docs/tutorials/deploy_to_production/installations/oss/ownserver/ruby/nginx/ as noted in the message at the top of that page.

Our build bot is intended to build packages that work with the Nginx available from the distro repos or if none exists then EPEL. Thus our CentOS 7 package works with Nginx 1.20.1 because that's what EPEL provides, and our CentOS 8 package works with 1.14.1 because that's what you get by default on CentOS 8. However I've heard that there are actually multiple versions of Nginx available on CentOS 8, via module streams, (https://github.com/phusion/passenger/issues/2360) so if someone knows how we could work with that system, it would be useful to know.

As for the Alma/Rocky/Bedrock/etc enterprise linux distros that have sprung up, we'll probably add support for one or more, it's just a matter of deciding whether to duplicate the build system for them or to have the repo serve these distros by ignoring the distro name. That'll depend on just how CentOS/RHEL compatible they turn out to be in practice.

**Comment by pgill98** [comment]
Hi @CamJN,

Thanks for getting back to me!

Yes, there are multiple versions of nginx available, and they can be enabled and disabled using built in commands (yum module enable nginx:1.20 / dnf module enable nginx:1.20) (https://dnf.readthedocs.io/en/latest/command_ref.html#module-command-label). It tells the distro to use the enabled module for that package when calling for package installs/downloads/etc. Currently, nginx 1.14 is the default enabled module for nginx. Out of curiosity, what is your team having troubles with when it comes to the modules and the build bot?

**Comment by CamJN** [comment]
The issue so far has just been finding information on what we need to do to our end to provide multiple module streams. We use `createrepo` to make our repo and manage the metadata and it looks like we'll have to migrate to `createrepo_c` which only just recently had some module stream functionality added: https://bugzilla.redhat.com/show_bug.cgi?id=1795936

**Comment by pgill98** [comment]
Hi @CamJN,

I was wondering how everything is going with implementing module streams and nginx_passenger module for different nginx versions? I know you guys probably have a bunch of things to work on dev wise, but thought I'd check in and see if you guys were working on this at all?

**Comment by CamJN** [comment]
No news worth reporting, perhaps you could suggest to the alma linux maintainers that documenting how to get multiple module streams packaged and hosted in a repo would be a great help.

**Comment by CamJN** [comment]
We switched the Nginx package passenger depends on to the newest stream available rather than the default.
